#!/bin/bash

docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/winds.c -o /data/winds.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -DINLINE=inline   -c

#sprites
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite/dirty.c -o /data/sprite/dirty.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -ISDL -DINLINE=inline   -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite/sdlutils.c -o /data/sprite/sdlutils.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include -DINLINE=inline   -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite/animation.c -o /data/sprite/animation.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite/bitmask.c -o /data/sprite/bitmask.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite/global.c -o /data/sprite/global.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite/sprite.c -o /data/sprite/sprite.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -c


#support
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/support/maths.c -o /data/support/maths.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -DINLINE=inline  -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/support/console.c -o /data/support/console.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/support/text.c -o /data/support/text.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/support/names.c -o /data/support/names.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c

#root
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/config.c -o /data/config.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -Isprite -I. -Isupport -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/mech.c -o /data/mech.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I. -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/players.c -o /data/players.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I. -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/level.c -o /data/level.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I. -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c

#sprite_types
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/explosions.c -o /data/sprite_types/explosions.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/missile.c -o /data/sprite_types/missile.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/energymeter.c -o /data/sprite_types/energymeter.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/hangar.c -o /data/sprite_types/hangar.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/bomb.c -o /data/sprite_types/bomb.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/airballoon.c -o /data/sprite_types/airballoon.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/bonusmachine.c -o /data/sprite_types/bonusmachine.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/cloud.c -o /data/sprite_types/cloud.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/bouncer.c -o /data/sprite_types/bouncer.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/zeppelin.c -o /data/sprite_types/zeppelin.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/mark.c -o /data/sprite_types/mark.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/parachute.c -o /data/sprite_types/parachute.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/biplane.c -o /data/sprite_types/biplane.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/dust.c -o /data/sprite_types/dust.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/bird.c -o /data/sprite_types/bird.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/bullet.c -o /data/sprite_types/bullet.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/fire.c -o /data/sprite_types/fire.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/puff.c -o /data/sprite_types/puff.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/smoke.c -o /data/sprite_types/smoke.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/message.c -o /data/sprite_types/message.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/blueplane.c -o /data/sprite_types/blueplane.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types/cannon.c -o /data/sprite_types/cannon.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c

#again root
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/airstrike.c -o /data/airstrike.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sprite_types.c -o /data/sprite_types.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/control.c -o /data/control.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm ozzyboshi/bebbo-amiga-gcc m68k-amigaos-gcc -noixemul -lm /data/sound.c -o /data/sound.o -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -c

# link
docker run -v /home/ozzy/rtg/airstrike/airstrike-amiga/src/:/data -t  --rm amigasdlgcc m68k-amigaos-gcc -noixemul -lm /data/winds.o /data/sprite/dirty.o /data/sprite/sdlutils.o /data/sprite/animation.o /data/sprite/bitmask.o /data/sprite/global.o /data/sprite/sprite.o /data/support/maths.o /data/support/console.o /data/support/text.o /data/support/names.o /data/config.o /data/mech.o /data/players.o /data/level.o /data/sprite_types/explosions.o /data/sprite_types/missile.o /data/sprite_types/energymeter.o /data/sprite_types/hangar.o /data/sprite_types/bomb.o /data/sprite_types/airballoon.o /data/sprite_types/bonusmachine.o /data/sprite_types/cannon.o /data/sprite_types/cloud.o /data/sprite_types/bouncer.o /data/sprite_types/zeppelin.o /data/sprite_types/mark.o /data/sprite_types/parachute.o /data/sprite_types/biplane.o /data/sprite_types/dust.o /data/sprite_types/bird.o /data/sprite_types/bullet.o /data/sprite_types/fire.o /data/sprite_types/puff.o /data/sprite_types/smoke.o /data/sprite_types/message.o /data/sprite_types/blueplane.o /data/airstrike.o /data/sprite_types.o /data/control.o /data/sound.o -o /data/airstrike -lSDL -ldebug -g -O2 -Wall -Wno-unused   -I/data/sprite -I/data/ -I/data/support -I/opt/amiga/include/SDL -I/opt/amiga/SDL_image-pack/include/SDL -DINLINE=inline   -D_GNU_SOURCE=1 -D_REENTRANT -L/opt/amiga/SDL_image-pack/lib -lSDL_image -ljpeg -lpng -L/opt/amiga/zlib-package/lib -lz